Repository metal3-io/community, pull requests merged in 2023-12, with the labels that each got.

#2 Add OWNERS file
  OWNERS
Labels: size/S

#3 Fix wrapping issues in ADOPTERS
  ADOPTERS.md
  hack/markdownlint.sh
Labels: size/M, approved, lgtm

#5 add clomonitor badge
  README.md
Labels: size/XS, approved, lgtm

#4 Add Contributor ladder, contributor role, governance and roadmap document
  CONTRIBUTOR-LADDER.md
  CONTRIBUTOR-ROLE.md
  GOVERNANCE.md
  ROADMAP.md
Labels: size/L, approved, lgtm

#7 Add Metal3 website link in README
  README.md
Labels: size/XS, approved, lgtm

#8 Update code of conduct
  CODE_OF_CONDUCT.md
Labels: size/M, approved, lgtm
